name: Semver
description: Generate semver
branding:
  icon: at-sign
  color: blue
inputs:
  value:
    description: Value to match the pattern on
    required: true
    default: ${{ github.ref_name }}
  identifier:
    description: Identifier to be used to prefix premajor, preminor, prepatch or prerelease version increments.
    required: false
  identifier-base:
    description: Base number to be used for the prerelease identifier.
        Can be either 0 or 1, or false to omit the number altogether.
        Defaults to 0.
    required: false
outputs:
  version:
    description: Parsed version string
  raw:
    description: Raw input version string
  next.premajor:
    description: Next premajor version
  next.preminor:
    description: Next preminor version
  next.prepatch:
    description: Next prepatch version
  next.major:
    description: Next major version
  next.minor:
    description: Next minor version
  next.patch:
    description: Next patch version
  next.prerelease:
    description: Next prerelease version
  major:
    description: Parsed Major version
  minor:
    description: Parsed minor version
  patch:
    description: Parsed patch version
  prerelease:
    description: Parsed prerelease version
  isPrerelease:
    description: Is the version a prerelease
  build:
    description: Parsed build version
  json:
    description: Parsed version as JSON
    value: ${{ steps.semver.outputs.result }}
runs:
  using: node20
  main: dist/index.js
