name: Semver
description: Generate semver
inputs:
  input:
    description: Input to match the pattern on
    required: true
    default: ${{ github.ref_name }}
  pattern:
    description: Semver pattern string
    required: true
    default: ^v?(?P<major>[0-9]+)(?:\.(?P<minor>[0-9]+))?(?:\.(?P<patch>[0-9]+))?(?:\-(?P<prerelease>[\w-]+))?(?:\+(?P<build>[\w-]+))?$
outputs:
  version:
    description: The full matched version string
    value: ${{ steps.semver.outputs.version }}
  major:
    description: Semver major version
    value: ${{ steps.semver.outputs.major }}
  minor:
    description: Semver minor version
    value: ${{ steps.semver.outputs.minor }}
  patch:
    description: Semver patch version
    value: ${{ steps.semver.outputs.patch }}
  prerelease:
    description: Semver prerelease version
    value: ${{ steps.semver.outputs.prerelease }}
  build:
    description: Semver build version
    value: ${{ steps.semver.outputs.build }}
  json:
    description: Semver build version
    value: ${{ steps.semver.outputs.json }}
runs:
  using: composite
  steps:
  - shell: python
    id: semver
    run: |
      from __future__ import print_function
      import re
      import os
      import json

      input = '${{ inputs.input }}'
      pattern = re.compile('${{ inputs.pattern }}')
      matched = pattern.match(input)

      if matched:
          groupdict = matched.groupdict()

          with open(os.environ['GITHUB_OUTPUT'], 'a') as fp:
              print('json={}'.format(json.dumps(groupdict)), file=fp)
              print('version={}'.format(matched.string), file=fp)

              for key, value in groupdict.items():
                  if not value:
                      continue

                  print('{key}={value}'.format(key=key, value=value), file=fp)
  - shell: bash
    run: |
      echo "::group::Output"
      yq e -P <<< '${{ steps.semver.outputs.json }}'
      echo "::endgroup::"
